### PR TITLE
Added mobile and anon page controls, and updated controls.

### PR DESCRIPTION
**Pull request by nathan-nz**
Hi Jay,

I've had a bit of a play and added some features that I am keen to have.

Part of this was merging in the functionality of https://github.com/tshenry/discourse-force-mobile-homepage, which uses the same field and was going to cause a conflict for my use-case.

I've also suggested a new title, dropping the '-for-groups' bit.

### CODE REVIEW

**Comment by pfaffman** [comment]
Err, looks good do me. Let's go for it!

**Comment by nathan-nz** [comment]
Ok - don't you have to merge it?

**Comment by pfaffman** [comment]
Oh. Darn. Sorry. I thought I'd merged it! I'll take another look in a bit..
Sorry about that!

**Comment by pfaffman** [comment]
Oh. Sigh. This cleared all of the settings on my site that I just tried this on. So apparentlyl this upgrade isn't backward compatible.

It's because you capitalized the settings. I'm going to go back and fix that.

**Comment by pfaffman** [comment]
OK. I changed the caps in those settings. All lower-case is pretty much the accepted standard, I'm pretty sure.

Fixing the caps un-broke the settings in my existing site (that I know about).

Thanks again for your help! Making it not break the thing that I base it on is much appreciated.

**Comment by nathan-nz** [comment]
Sorry about that! I must have done it in a moment of madness. Glad it was easy to fix.

**Pull request merged**
